### ISSUE TITLE
Pagination writes an error when new callbackHandler added

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/inline-keyboard-pagination#5]
Hi!
I added my new callback handler in hook.php:

```php
CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) use ($telegram) {
        if ($query->getData() === 'gostart') {
            return Request::editMessageText([
                'chat_id' => $query->getMessage()->getChat()->getId(),
                'message_id' => $query->getMessage()->getMessageId(),
                'text' => $query->getData(),
                'reply_markup' => AboutCommand::getMyInlineKeyboard(),
            ]);
        }
    });
```

And! If I click on any InlineKeyboardButton in my bot (no matter in which command): I've get an error in log:

```
[:error] [pid 7455] [client 149.154.167.216:55200] PHP Notice:  Undefined index: command in /var/www/www-root/data/www/_/Commands/UserCommands/PortfolioCommand.php on line 39
```
Okay, look at my PortfolioCommand (thanks @noplanman )
```php
class PortfolioCommand extends UserCommand
{
    ...

    public static function callbackHandler(CallbackQuery $query)
    {
        $params = InlineKeyboardPagination::getParametersFromCallbackData($query->getData());
        if ($params['command'] !== 'portfolio') { // 39 line. Error is here
            return null;
        }

        $data = [
            'chat_id'    => $query->getMessage()->getChat()->getId(),
            'message_id' => $query->getMessage()->getMessageId(),
            'text'       => 'Empty',
            'parse_mode' => 'Markdown',
        ];

        // Using pagination
        if ($pagination = self::getInlineKeyboardPagination($params['newPage'])) {
            $getData = DB::getPdo()->query("SELECT * FROM `portfolio` WHERE `id` = '" . intval($params['newPage']) . "' LIMIT 1")->fetch();
            $data['text']         = self::getPaginationContent($pagination['items']);
            $data['reply_markup'] = [
                'inline_keyboard' => [
                    [
                        ['text' => '🤖 Open', 'url' => 'https://google.com'],
                        ['text' => '📖 More...', 'url' => $getData['link']]
                    ],
                    $pagination['keyboard'],
                ],
            ];
        }

        return Request::editMessageText($data);
    }
}
```

I tried to fix that:
```php
if (isset($params['command']) && $params['command'] !== 'portfolio') {
            return null;
}
```

And get 2 new errors:
```
[:error] [pid 7735] [client 149.154.167.216:56227] PHP Notice:  Undefined index: newPage in /var/www/www-root/data/www/_/Commands/UserCommands/PortfolioCommand.php on line 51
```
And
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to TelegramBot\\InlineKeyboardPagination\\InlineKeyboardPagination::__construct() must be of the type integer, null given, called in /var/www/www-root/data/www/_/Commands/UserCommands/PortfolioCommand.php on line 97 and defined in /var/www/www-root/data/www/_/vendor/php-telegram-bot/inline-keyboard-pagination/src/InlineKeyboardPagination.php:211
Stack trace:
#0 /var/www/www-root/data/www/_/Commands/UserCommands/PortfolioCommand.php(97): TelegramBot\\InlineKeyboardPagination\\InlineKeyboardPagination->__construct(Array, 'portfolio', NULL, 1)
#1 /var/www/www-root/data/www/_/Commands/UserCommands/PortfolioCommand.php(51): Longman\\TelegramBot\\Commands\\UserCommands\\PortfolioCommand::getInlineKeyboardPagination(NULL)
#2 /var/www/www-root/data/www/_/vendor/longman/telegram-bot/src/Commands/SystemCommands/CallbackqueryCommand.php(56): Longman\\TelegramBot\\Commands\\UserCommands\\PortfolioCommand::callbackHandler(Object(Lon in /var/www/www-root/data/www/_/vendor/php-telegram-bot/inline-keyboard-pagination/src/InlineKeyboardPagination.php on line 211
```

How can I fix that? Thanks in advance!

**Comment by noplanman** [comment]
What does your `PortfolioCommand::getInlineKeyboardPagination` and `AboutCommand::getMyInlineKeyboard` method look like?

**Comment by MyZik** [comment]
@noplanman Here is `PortfolioCommand::getInlineKeyboardPagination`

```php
public static function getInlineKeyboardPagination($page = 1)
    {
        $portfolio   = self::getPortfolio();

        if (empty($portfolio)) {
            return null;
        }

        // Define inline keyboard pagination.
        $ikp = new InlineKeyboardPagination($portfolio, 'portfolio', $page, self::$per_page);

        // If item count changes, take wrong page clicks into account.
        try {
            $pagination = $ikp->getPagination();
        } catch (InlineKeyboardPaginationException $e) {
            $pagination = $ikp->getPagination(1);
        }

        return $pagination;
    }
```

And `AboutCommand::getMyInlineKeyboard`:
```php
public static function getMyInlineKeyboard()
    {
        $keyboard = new InlineKeyboard(
            [
                ['text' => 'About', 'callback_data' => 'about_us'],
                ['text' => 'Team', 'callback_data' => 'about_team'],
            ],
            [
                ['text' => 'Contacts', 'callback_data' => 'about_contacts'],
                ['text' => 'Cooperation', 'callback_data' => 'about_cooperation'],
            ]
        );
        return $keyboard;
    }
```

**Comment by noplanman** [comment]
I can't see where you are calling or assigning `PortfolioCommand::callbackHandler`.
Because it seems there is an issue with the inline keyboard pagination when calling it.

**Comment by MyZik** [comment]
@noplanman i think that problem in callBackhandler in hook.php.
If I delete the code, all works... But why?

So you can create a pagination command and use callbackHandler in hook.php and you'll get errors in error.log :(
